version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: internship_tracker
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
